apiVersion: v1
kind: Namespace
metadata:
  name: model-eval
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
    security.platform/zone: evaluation
  annotations:
    openshift.io/display-name: "Model Security - Evaluation Zone"
