apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-registry-db
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry-db
    app.kubernetes.io/part-of: ai-model-security-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
