apiVersion: v1
kind: Namespace
metadata:
  name: model-ingress
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
    security.platform/zone: ingress
  annotations:
    openshift.io/display-name: "Model Security - Ingress Zone"
