apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - scc-rolebinding.yaml
  - triggers-eventlistener-rolebinding.yaml
  - triggers-eventlistener-clusterrolebinding.yaml
