apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-eval-pipeline-scc
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
subjects:
  - kind: ServiceAccount
    name: model-eval-pipeline
