# Keep in sync with instances/model-test/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: model-test
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
    security.platform/zone: test
  annotations:
    openshift.io/display-name: "Model Security - Test Zone"
