apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingress-models
  namespace: model-ingress
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
    storage.platform/role: untrusted-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
