apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verified-models
  namespace: model-prod
  labels:
    app.kubernetes.io/part-of: ai-model-security-pipeline
    storage.platform/role: verified-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
